permalink: /:title 
paginate: 100
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile"]
auto: true
pygments: true
author:
    name: 存中
title : 奚適而惡乎待哉
tagline: 承載思想與文字之厚重

url : http://blq.asia