collections:
  Notes:
    output: true
    permalink: /:name/
  Pages:
    output: true
    permalink: /:name/
  blq:
    output: true
    permalink: /:name/
  Projects:
    output: true
    permalink: /:name/

permalink: /:title/
post_defaults:
  layout: post
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "hard_wrap"]

timezone: Asia/Shanghai
title : 奚適而惡乎待哉
tagline: 承載思想與文字之厚重
author:
  name: 存中
  email: cunzhong@qq.com
