collections:
  Notes:
    output: true
    permalink: /:path/
  blq:
    output: true
  Projects:
    output: true
    permalink: /:path/

permalink: /:title
post_defaults:
  layout: post
highlighter: pygments
kramdown:
  input: GFM
  toc_levels: "4"

timezone: Asia/Shanghai
title : 奚適而惡乎待哉
tagline: 承載思想與文字之厚重
author:
  name: 存中
  email: cunzhong@qq.com
