collections:
- notes
permalink: /:title
post_defaults:
  layout: post
pygments: true
markdown: rdiscount

timezone: Asia/Shanghai
title : 奚適而惡乎待哉
tagline: 承載思想與文字之厚重
author:
  name: 存中
  email: cunzhong@qq.com
