collections:
  Notes:
    output: true
    permalink: /:name/
  Pages:
    output: true
    permalink: /:name/
  blq:
    output: true
    permalink: /:name/
  Projects:
    output: true
    permalink: /:name/

permalink: /:title/
post_defaults:
  layout: post
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify", "hard_wrap", "footnotes", "lax_spacing"]
#kramdown:
#  input: GFM

timezone: Asia/Shanghai
title : 奚適而惡乎待哉
tagline: 承載思想與文字之厚重
author:
  name: 存中
  email: cunzhong@qq.com
